/*
  *
  * large header comment
  *
  */
public class NewClass {

  Integer newField;

  public NewClass(Integer value){
    newField = value;
    value = 5;
  }
  
  // comment \ca for TST3 as domain data was loaded with \ca and \us
  
  private void unused3(){}
  private void unused22(){}
  private void unused4(){}
  private void unused5(){}
  private void unused6(){}
  private void unused7(){}
  private void unused8(){}
  

  /*
  * This is fine.
  */
  public boolean isBadExample(){
    return true;
  }
  
  /*
  * This is fine.
  */
  public boolean isBadExampleTheSecond(){
    return true;
  }
  

private void unused(){}

//Comment for empty method
private void unused2(Integer param){
  param = 6;
}

//Comment for empty method
private void unused2(Integer param){
  param = 6;
}
 
private void unused22(Integer param){
  param = 6;
}
 
 private void unused222(Integer param){
  param = 6;
}


}
